
加载 Minari 数据集: mujoco/pusher/expert-v0
开始训练 FQL baseline...
































































































































































































































































Epoch 1/20: 100%|███████████████████████████████████████████████████████████████▉| 1892/1895 [09:10<00:00,  3.88it/s]
Epoch 1/20: 100%|████████████████████████████████████████████████████████████████| 1895/1895 [09:10<00:00,  3.44it/s]




































































































































































































































































Epoch 2/20: 100%|███████████████████████████████████████████████████████████████▉| 1893/1895 [08:43<00:00,  3.80it/s]
Epoch 2/20: 100%|████████████████████████████████████████████████████████████████| 1895/1895 [08:44<00:00,  3.62it/s]

































































































































































































































Epoch 3/20:  88%|███████████████████████████████████████████████████       | 1670/1895 [07:35<01:02,  3.59it/s]Exception ignored in: <generator object HDF5Storage.get_episodes at 0x000001B6A93084A0>
Traceback (most recent call last):
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\minari\dataset\_storages\hdf5_storage.py", line 130, in get_episodes
    with h5py.File(self._file_path, "r") as file:
  File "h5py/_objects.pyx", line 56, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 57, in h5py._objects.with_phil.wrapper
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\h5py\_hl\files.py", line 648, in __exit__
    self.close()
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\h5py\_hl\files.py", line 630, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
KeyboardInterrupt:
Epoch 3/20:  88%|███████████████████████████████████████████████████▏      | 1673/1895 [07:36<01:02,  3.54it/s]Exception ignored in: <generator object HDF5Storage.get_episodes at 0x000001B6A93084A0>
Traceback (most recent call last):
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\minari\dataset\_storages\hdf5_storage.py", line 130, in get_episodes
    with h5py.File(self._file_path, "r") as file:
  File "h5py/_objects.pyx", line 56, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 57, in h5py._objects.with_phil.wrapper
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\h5py\_hl\files.py", line 648, in __exit__
    self.close()
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\h5py\_hl\files.py", line 630, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
KeyboardInterrupt:
Epoch 3/20:  88%|███████████████████████████████████████████████████▎      | 1675/1895 [07:36<01:00,  3.67it/s]
Traceback (most recent call last):
  File "d:\PycharmProjects\MyReinFlow\reflow\ft_baselines\fql_main.py", line 590, in <module>
  File "d:\PycharmProjects\MyReinFlow\reflow\ft_baselines\fql_main.py", line 580, in main
  File "d:\PycharmProjects\MyReinFlow\reflow\ft_baselines\fql_main.py", line 365, in train
    q_weight = 0.0 if epoch < 1 else (0.5 if epoch < 3 else 1.0)
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\torch\utils\data\dataloader.py", line 733, in __next__
    data = self._next_data()
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\torch\utils\data\dataloader.py", line 789, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "d:\PycharmProjects\MyReinFlow\reflow\ft_baselines\fql_main.py", line 159, in __getitem__
    ep = self.ds[ep_idx]  # type: ignore
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\minari\dataset\minari_dataset.py", line 298, in __getitem__
    return next(episode)
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\minari\dataset\_storages\hdf5_storage.py", line 132, in get_episodes
    ep_group = file[f"episode_{ep_idx}"]
  File "h5py/_objects.pyx", line 56, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 57, in h5py._objects.with_phil.wrapper
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\h5py\_hl\group.py", line 360, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 56, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 57, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 257, in h5py.h5o.open
  File "h5py/h5i.pyx", line 47, in h5py.h5i.wrap_identifier
  File "<frozen importlib._bootstrap>", line 404, in parent
KeyboardInterrupt
Traceback (most recent call last):
  File "d:\PycharmProjects\MyReinFlow\reflow\ft_baselines\fql_main.py", line 590, in <module>
  File "d:\PycharmProjects\MyReinFlow\reflow\ft_baselines\fql_main.py", line 580, in main
  File "d:\PycharmProjects\MyReinFlow\reflow\ft_baselines\fql_main.py", line 365, in train
    q_weight = 0.0 if epoch < 1 else (0.5 if epoch < 3 else 1.0)
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\torch\utils\data\dataloader.py", line 733, in __next__
    data = self._next_data()
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\torch\utils\data\dataloader.py", line 789, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "d:\PycharmProjects\MyReinFlow\reflow\ft_baselines\fql_main.py", line 159, in __getitem__
    ep = self.ds[ep_idx]  # type: ignore
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\minari\dataset\minari_dataset.py", line 298, in __getitem__
    return next(episode)
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\minari\dataset\_storages\hdf5_storage.py", line 132, in get_episodes
    ep_group = file[f"episode_{ep_idx}"]
  File "h5py/_objects.pyx", line 56, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 57, in h5py._objects.with_phil.wrapper
  File "C:\Users\32293\.conda\envs\xuance\lib\site-packages\h5py\_hl\group.py", line 360, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 56, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 57, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 257, in h5py.h5o.open
  File "h5py/h5i.pyx", line 47, in h5py.h5i.wrap_identifier
  File "<frozen importlib._bootstrap>", line 404, in parent
KeyboardInterrupt